[global]
# name of this server
name=arp-lan1
# Ethernet and IP4 processes send requests to this name
cfg-name=arp-lan1-cfg
# TAP/promiscuous device to send packets to
out-name=tap-test-lan1
resolver-name=arp-lan1-resolver
meta-name=arp-enp1s0-meta
ether-meta-name=promisc-enp1s0-meta
ip4-meta-name=ip4-enp1s0-meta

[specific]
msg-queue-size=16384
mtu-size=1500
# channel via which ip4 server asks to resolve an address

# MAC seperated with :
[mappings]
