[global]
# my name, where tcp layer sends to (incoming requests)
lower-in-name=gopher-lan1-lower
name-meta=gopher-lan1-meta
# gopher -> tcp
out-name=tcp-lan1-upper

[specific]
msg-queue-size=8192
base-path=./gopher
hostname=192.168.1.2
