[global]
# my name, where ip layer sends to (incoming requests)
lower-in-name=icmp-lan1-lower
# icmp -> ip
out-name=ip4-lan1-upper
# e.g. "connection refused" packet from ip4
error-in-name=icmp-lan1-error

[specific]
msg-queue-size=16384
