[global]
# my name, where ip layer sends to (incoming requests)
lower-in-name=icmp-lan1-lower
# icmp -> ip
out-name=ip4-lan1-upper
# e.g. "connection refused" packet from ip4
error-in-name=icmp-lan1-error

[specific]
# ip packets can get quite big
# too short a buffer can stall processing
msg-queue-size=151000
