[global]
# Eth -> ip
lower-in-name=ip4-lan1-lower
# ip announce to arp
cfg-name=arp-lan1-cfg
# ip -> Eth
out-name=tap-test-lan1
# tcp/udp/icmp -> ip
upper-in-name=ip4-lan1-upper

[specific]
msg-queue-size=16384
announce-ip4-addr=arp-lan1-cfg
listen-addr=192.168.1.2/24
default-gw=192.168.1.1
# for errors (e.g. connection refused)
icmp-name=icmp-lan1-lower
# my name in the resolver shm
resolver-replies=ip4-lan1-resrepl
# name of the resolver shm
resolver-name=arp-lan1-resolver

[mappings]
# decimal-protocol-number=name-of-server
1=icmp-lan1-lower
17=udp-lan1-lower
