[global]
name=promisc-test-lan1
run-as=1000
run-group-as=1000
meta-name=promisc-test-lan1-meta

[specific]
# Ethernet device to connect to
dev=enx00e04cfa0e77
msg-queue-size=16384
mtu-size=1500
announce-mac-name=arp-lan1-cfg

[mappings]
0x0806=arp-lan1
0x0800=ip4-lan1-lower
