[global]
# my name, where ip layer sends to (incoming requests)
lower-in-name=tcp-lan1-lower
# tcp -> ip
out-name=ip4-lan1-upper
# x -> tcp
name-upper=tcp-lan1-upper

[specific]
msg-queue-size=151000
icmp-error-name=icmp-lan1-error

[mappings]
80=http-lan1-lower,http-lan1-meta
