[global]
# my name, where ip layer sends to (incoming requests)
lower-in-name=udp-lan1-lower
# udp -> ip
out-name=ip4-lan1-upper
# x -> udp
name-upper=udp-lan1-upper

[specific]
msg-queue-size=16384

[mappings]
123=ntp-lan1-lower
